#!/usr/bin/env node

// Build script to generate environment configuration for deployment
// This runs during the Netlify build and injects real env var values into env-config.js
// Run automatically via: npm run build

const fs = require('fs');
const path = require('path');

// Collect environment variables (set in Netlify dashboard)
const supabaseUrl = process.env.SUPABASE_URL || '';
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || '';
const geminiKey = process.env.GEMINI_API_KEY || '';
const openaiKey = process.env.OPENAI_API_KEY || '';
const cohereKey = process.env.COHERE_API_KEY || '';
const huggingfaceKey = process.env.HUGGINGFACE_API_KEY || '';
const togetherKey = process.env.TOGETHER_API_KEY || '';
const anthropicKey = process.env.ANTHROPIC_API_KEY || '';

// Warn if critical keys are missing
if (!supabaseUrl || !supabaseAnonKey) {
  console.warn('⚠️  WARNING: SUPABASE_URL or SUPABASE_ANON_KEY is not set!');
  console.warn('   Authentication will NOT work. Set these in Netlify > Site Settings > Environment Variables.');
}

if (!geminiKey && !openaiKey && !cohereKey && !anthropicKey) {
  console.warn('⚠️  WARNING: No AI API keys are set! AI chat will not work.');
  console.warn('   Set at least one of: GEMINI_API_KEY, OPENAI_API_KEY, COHERE_API_KEY, ANTHROPIC_API_KEY');
}

const envConfig = `// Environment Configuration - Auto-generated during Netlify build
// Do NOT edit this file manually - edit build-config.js instead
window.ENV = {
  SUPABASE_URL: '${supabaseUrl}',
  SUPABASE_ANON_KEY: '${supabaseAnonKey}',
  GEMINI_API_KEY: '${geminiKey}',
  OPENAI_API_KEY: '${openaiKey}',
  COHERE_API_KEY: '${cohereKey}',
  HUGGINGFACE_API_KEY: '${huggingfaceKey}',
  TOGETHER_API_KEY: '${togetherKey}',
  ANTHROPIC_API_KEY: '${anthropicKey}'
};

// Runtime check
(function() {
  var missing = [];
  if (!window.ENV.SUPABASE_URL) missing.push('SUPABASE_URL');
  if (!window.ENV.SUPABASE_ANON_KEY) missing.push('SUPABASE_ANON_KEY');

  if (missing.length > 0) {
    console.warn('[PreAid] Missing environment variables:', missing.join(', '));
    console.warn('[PreAid] Authentication will not work until these are configured in Netlify.');
  } else {
    console.log('[PreAid] Environment loaded successfully.', {
      hasSupabaseUrl: !!window.ENV.SUPABASE_URL,
      hasSupabaseKey: !!window.ENV.SUPABASE_ANON_KEY,
      hasGeminiKey: !!window.ENV.GEMINI_API_KEY
    });
  }
})();
`;

const outputPath = path.join(__dirname, 'env-config.js');
fs.writeFileSync(outputPath, envConfig, 'utf8');
console.log('✅ env-config.js generated successfully at:', outputPath);
console.log('   SUPABASE_URL:', supabaseUrl ? '✅ Set' : '❌ MISSING');
console.log('   SUPABASE_ANON_KEY:', supabaseAnonKey ? '✅ Set' : '❌ MISSING');
console.log('   GEMINI_API_KEY:', geminiKey ? '✅ Set' : '❌ Not set');
console.log('   OPENAI_API_KEY:', openaiKey ? '✅ Set' : '❌ Not set');
console.log('   COHERE_API_KEY:', cohereKey ? '✅ Set' : '❌ Not set');
