// Environment Configuration
// NOTE: This file is auto-generated by build-config.js during Netlify build.
// The REAL values are injected at build time from Netlify Environment Variables.
// Do NOT put real keys here — they get replaced automatically.
window.ENV = {
  SUPABASE_URL: '',
  SUPABASE_ANON_KEY: '',
  GEMINI_API_KEY: '',
  OPENAI_API_KEY: '',
  COHERE_API_KEY: '',
  HUGGINGFACE_API_KEY: '',
  TOGETHER_API_KEY: '',
  ANTHROPIC_API_KEY: ''
};

// Check if keys are present and warn if missing
(function() {
  var missing = [];
  if (!window.ENV.SUPABASE_URL) missing.push('SUPABASE_URL');
  if (!window.ENV.SUPABASE_ANON_KEY) missing.push('SUPABASE_ANON_KEY');

  if (missing.length > 0) {
    console.warn('[PreAid] Missing environment variables:', missing.join(', '));
    console.warn('[PreAid] Make sure these are set in Netlify Environment Variables and a new deploy was triggered.');
  } else {
    console.log('[PreAid] Environment loaded successfully:', {
      hasSupabaseUrl: !!window.ENV.SUPABASE_URL,
      hasSupabaseKey: !!window.ENV.SUPABASE_ANON_KEY,
      hasGeminiKey: !!window.ENV.GEMINI_API_KEY
    });
  }
})();